ALTER TABLE ads ADD COLUMN display_mode TEXT NOT NULL DEFAULT 'always';
ALTER TABLE ads ADD COLUMN delay_seconds INTEGER NOT NULL DEFAULT 1;
ALTER TABLE ads ADD COLUMN start_at TEXT;
ALTER TABLE ads ADD COLUMN end_at TEXT;

CREATE TABLE IF NOT EXISTS ad_stats (
  position_key TEXT PRIMARY KEY,
  impressions INTEGER NOT NULL DEFAULT 0,
  clicks INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
